import { it, expect } from 'vitest';
import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { ALL_DLC_PACKS } from '../data/dlc';
import { LINKS } from '../data/dlc/links';
import { SEED_DECK } from '../data/seedDeck';
import { ALL_GLYPHS } from '../engine/glyphBank';
import type { CardDef } from '../engine/types';

// SITE DATA GENERATOR — emits site/data.js (window.GBG_DATA) for the static relational browser in
// site/. Inert during `npm test` (it.runIf); run explicitly to regenerate:
//   GEN_SITE=1 npx vitest run src/site/genData.test.ts
// Source of truth = the curated DLC packs + base seed deck + authored influence links + glyph banks,
// so the site never drifts from the engine's data.

interface SiteCard {
  id: string; name: string; cls: string; text: string;
  glyphs: string[]; correspondences: Record<string, string>;
  sourceRef: string; portal?: string; packs: string[];
}

function build() {
  // Cards: dedupe by id, collect every pack a card appears in (patrons recur across packs).
  const byId = new Map<string, SiteCard>();
  const packMeta: { id: string; name: string; description: string; count: number }[] = [];

  const add = (c: CardDef, packId: string) => {
    const ex = byId.get(c.id);
    if (ex) { if (!ex.packs.includes(packId)) ex.packs.push(packId); return; }
    byId.set(c.id, {
      id: c.id, name: c.name, cls: c.cls, text: c.text, glyphs: c.glyphs,
      correspondences: c.correspondences, sourceRef: c.sourceRef,
      ...(c.portal ? { portal: c.portal } : {}), packs: [packId],
    });
  };

  for (const p of ALL_DLC_PACKS) {
    packMeta.push({ id: p.id, name: p.name, description: p.description, count: p.cards.length });
    for (const c of p.cards) add(c, p.id);
  }
  // Base seed cards (so links into leary:/raw:/base ids resolve in the browser).
  packMeta.push({ id: 'seed', name: 'Base Seed Deck', description: 'The grounded starter cards the game ships with.', count: SEED_DECK.length });
  for (const c of SEED_DECK) add(c, 'seed');

  const cards = [...byId.values()].sort((a, b) => a.name.localeCompare(b.name));

  // Only keep links whose endpoints are both present (defensive — dead links are skipped in-engine too).
  const ids = new Set(cards.map((c) => c.id));
  const links = LINKS.filter((l) => ids.has(l.a) && ids.has(l.b));

  const glyphs: Record<string, { glyph: string; label: string; meaning: string; category: string }> = {};
  for (const g of ALL_GLYPHS) glyphs[g.id] = { glyph: g.glyph, label: g.label, meaning: g.meaning, category: g.category };

  // Synthesize display entries for glyph ids referenced by cards but outside the four banks (e.g. the
  // base seed deck's `mercurius`, the philosophical Mercurius / spirit of the Game). Guarantees the
  // browser can always render a symbol for every card glyph.
  const ALIASES: Record<string, { glyph: string; label: string; meaning: string; category: string }> = {
    mercurius: { glyph: '☿', label: 'Mercurius', meaning: 'Philosophical mercury — the volatile, mediating spirit of the Game; the seed-deck’s mark of correspondence.', category: 'principle' },
  };
  for (const c of cards) for (const id of c.glyphs) {
    if (glyphs[id]) continue;
    glyphs[id] = ALIASES[id] ?? { glyph: '◈', label: id, meaning: 'An attribute of this bead.', category: 'other' };
  }

  return { packs: packMeta, cards, links, glyphs };
}

it.runIf(process.env.GEN_SITE)('writes site/data.js', () => {
  const data = build();
  const dir = join(process.cwd(), 'site');
  mkdirSync(dir, { recursive: true });
  const banner = '// AUTO-GENERATED by src/site/genData.test.ts — do not edit by hand.\n';
  writeFileSync(join(dir, 'data.js'), `${banner}window.GBG_DATA = ${JSON.stringify(data)};\n`, 'utf8');
  expect(data.cards.length).toBeGreaterThan(100);
});

// Always-on sanity check (runs in npm test): the data builds and is internally consistent.
it('site data builds with resolvable links', () => {
  const data = build();
  expect(data.cards.length).toBeGreaterThan(100);
  expect(data.links.length).toBeGreaterThan(40);
  const ids = new Set(data.cards.map((c) => c.id));
  for (const l of data.links) { expect(ids.has(l.a)).toBe(true); expect(ids.has(l.b)).toBe(true); }
  // every glyph referenced by a card has a definition (so the site can render its symbol)
  const glyphIds = new Set(Object.keys(data.glyphs));
  for (const c of data.cards) for (const g of c.glyphs) expect(glyphIds.has(g)).toBe(true);
});
